######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 29 19:41:14 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h passwordedit.h
SOURCES += mainwindow.cpp passwordedit.cpp test.cpp


