######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 4 18:29:17 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digitalClock.h
SOURCES += digitalClock.cpp main.cpp
