######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 21 18:51:34 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bin_board.h CustomQWidget.h text_edit.h
SOURCES += bin_board.cpp textbin.cpp
